// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	authority "zero-server/server/internal/handler/authority"
	dictionary "zero-server/server/internal/handler/dictionary"
	menu "zero-server/server/internal/handler/menu"
	operation "zero-server/server/internal/handler/operation"
	test "zero-server/server/internal/handler/test"
	user "zero-server/server/internal/handler/user"
	"zero-server/server/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/user/login",
				Handler: user.LoginHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.OperationRecord},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/user/register",
					Handler: user.RegisterHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/user/edit",
					Handler: user.EditHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/user/changePass",
					Handler: user.ChangePassHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/user/sendIdentityMes",
					Handler: user.SendIdentityMesHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/user/getUserList",
					Handler: user.GetUserListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/user/setUserAuthority",
					Handler: user.SetUserAuthorityHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/user/deleteUser",
					Handler: user.DeleteUserHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/menu/list",
				Handler: menu.MenuListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/menu/getMenuList",
				Handler: menu.GetMenuListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/menu/addBaseMenu",
				Handler: menu.AddBaseMenuHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/menu/deleteMenu",
				Handler: menu.DeleteMenuHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/menu/editMenu",
				Handler: menu.EditMenuHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/menu/getMenuAuthority",
				Handler: menu.GetMenuAuthorityHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/menu/addMenuAuthority",
				Handler: menu.AddMenuAuthorityHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/menu/getUserMenus",
				Handler: menu.GetUserMenusHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/authority/getAuthorityList",
				Handler: authority.GetAuthorityListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/authority/createAuthority",
				Handler: authority.CreateAuthorityHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/authority/deleteAuthority",
				Handler: authority.DeleteAuthorityHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/authority/updateAuthority",
				Handler: authority.UpdateAuthorityHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/authority/setDataAuthority",
				Handler: authority.SetDataAuthorityHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/test/testInter",
				Handler: test.TestHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/dic/getDicList",
				Handler: dictionary.GetDicListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/dic/getDicDetials",
				Handler: dictionary.GetDicDetailsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/dic/addDic",
				Handler: dictionary.AddDicHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/dic/editDic",
				Handler: dictionary.EditDicHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/dic/deleteDic",
				Handler: dictionary.DeleteDicHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/dic/addDicDetails",
				Handler: dictionary.AddDicDetailsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/dic/editDicDetails",
				Handler: dictionary.EditDicDetailsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/dic/deleteDicDetails",
				Handler: dictionary.DeleteDicDetailsHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/operation/getOperationList",
				Handler: operation.GetOperationListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/operation/createOperation",
				Handler: operation.CreateOperationHandler(serverCtx),
			},
		},
	)
}
