// Code generated by goctl. DO NOT EDIT.
package types

type LoginRequset struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResponse struct {
	Message     string `json:"message"`
	Token       string `json:"token"`
	Id          int    `json:"id"`
	AuthorityId int    `json:"authorityId"`
}

type EditUserRequest struct {
	Id           int64   `json:"id"`
	Username     string  `json:"username"`
	Phone        string  `json:"phone"`
	Email        string  `json:"email"`
	Enable       int64   `json:"enable"`
	AuthorityIds []int64 `json:"authorityIds"`
}

type EditUserResponse struct {
	Message string `json:"message"`
	Code    int64  `json:"code"`
}

type RegisterReq struct {
	Username     string  `json:"username"`
	Phone        string  `json:"phone"`
	Email        string  `json:"email,optional"`
	Password     string  `json:"password"`
	Enabled      int64   `json:"enable"`
	AuthorityId  int64   `json:"authorityId"`
	AuthorityIds []int64 `json:"authorityIds"`
}

type RegisterResp struct {
	Message string `json:"message"`
}

type SendIdentityMesReq struct {
	Phone string `json:"phone"`
}

type SendIdentityMesResp struct {
	Message string `json:"message"`
}

type ChangePasswordReq struct {
	UserId         int64  `json:"userId"`
	PriPassword    string `json:"priPassword"`
	ChangePassword string `json:"changePassword"`
}

type ChangePasswordResp struct {
	Message string `json:"message"`
}

type UserListReq struct {
	PageNum  int64 `json:"page"`
	PageSize int64 `json:"pageSize"`
}

type UserListResp struct {
	Page     int64          `json:"page"`
	PageSize int64          `json:"pageSize"`
	UserList []*UserMessage `json:"userList"`
	Total    int64          `json:"total"`
}

type UserMessage struct {
	Id          int64        `json:"id"`
	Username    string       `json:"username"`
	Phone       string       `json:"phone"`
	Email       string       `json:"email"`
	CreateTime  int64        `json:"createTime"`
	UpdateTime  int64        `json:"updateTime"`
	AuthorityId int64        `json:"authorityId"`
	Enable      int          `json:"enable"`
	Uuid        string       `json:"uuid"`
	Authorities []*Authority `json:"authorities"`
}

type Authority struct {
	CreateAt      int64  `json:"createAt"`
	UpdateAt      int64  `json:"updateAt"`
	AuthorityId   int64  `json:"authorityId"`
	AuthorityName string `json:"authorityName"`
	ParentId      int64  `json:"parentId"`
}

type SetUserAuthorityReq struct {
	AuthorityId []int64 `json:"authorityId"`
	UserId      int64   `json:"userId"`
}

type SetUserAuthorityResp struct {
	Message string `json:"message"`
}

type DeleteUserReq struct {
	Id int64 `json:"id"`
}

type DeleteUserResp struct {
	Message string `json:"message"`
}

type MenuRequest struct {
	Id int `json:"id"`
}

type MenuResponse struct {
	Resp string `json:"resp"`
}

type Menu struct {
	Id        int     `json:"id"`
	CreatedAt int64   `json:"createdAt,optional"`
	UpdatedAt int64   `json:"updatedAt,optional"`
	ParentId  string  `json:"parentId,optional"`
	Path      string  `json:"path,optional"`
	Name      string  `json:"name,optional"`
	Hidden    bool    `json:"hidden,optional"`
	Sort      int     `json:"sort,optional"`
	KeepAlive bool    `json:"keepAlive,optional"`
	Title     string  `json:"title,optional"`
	Icon      string  `json:"icon,optional"`
	CloseTab  int     `json:"closeTab,optional"`
	Children  []*Menu `json:"children,optional"`
}

type GetMenuListReq struct {
}

type GetMenuListResp struct {
	Total    int     `json:"total"`
	MenuList []*Menu `json:"menuList"`
}

type AddMenuReq struct {
	ParentId  string `json:"parentId"`
	Path      string `json:"path"`
	Name      string `json:"name"`
	Hidden    bool   `json:"hidden"`
	Sort      int    `json:"sort"`
	KeepAlive bool   `json:"keepAlive"`
	Title     string `json:"title"`
	Icon      string `json:"icon ,optional"`
	CloseTab  int    `json:"closeTab, optional"`
}

type AddMenuResp struct {
	Message string `json:"message"`
}

type DeleteMenuReq struct {
	Id int64 `json:"id"`
}

type DeleteMenuResp struct {
	Message string `json:"message"`
}

type EditMenuReq struct {
	Id        int64  `json:"id"`
	Path      string `json:"path"`
	Name      string `json:"name"`
	Hidden    bool   `json:"hidden"`
	Sort      int    `json:"sort"`
	KeepAlive bool   `json:"keepAlive"`
	Title     string `json:"title"`
	Icon      string `json:"icon, optional"`
	CloseTab  int    `json:"closeTab ,optional"`
}

type EditMenuResp struct {
	Message string `json:"message"`
}

type GetMenuAuthorityReq struct {
	AuthorityId int64 `json:"authorityId"`
}

type GetMenuAuthorityResp struct {
	MenuList []*Menu `json:"menuList"`
}

type AddMenuAuthorityReq struct {
	MenuList    []*Menu `json:"menuList"`
	AuthorityId int64   `json:"authorityId"`
}

type AddMenuAuthorityResp struct {
	Message string `json:"message"`
}

type GetUserMenusReq struct {
	UserId int `form:"userId"`
}

type GetUserMenusResp struct {
	MenuList []*Menu `json:"menuList"`
}

type CreateAuthorityReq struct {
	AuthorityId   int64  `json:"authorityId"`
	AuthorityName string `json:"authorityName"`
	ParentId      int64  `json:"parentId"`
}

type CreateAuthorityResp struct {
	Message string `json:"message"`
}

type GetAuthorityListReq struct {
	PageNum  int64 `json:"pageNum,optional"`
	PageSize int64 `json:"pageSize,optional"`
}

type GetAuthorityList struct {
	CreateAt      int64               `json:"createAt"`
	UpdateAt      int64               `json:"updateAt"`
	AuthorityId   int64               `json:"authorityId"`
	AuthorityName string              `json:"authorityName"`
	ParentId      int64               `json:"parentId"`
	Children      []*GetAuthorityList `json:"children"`
}

type GetAuthorityListResp struct {
	AuthorityList []*GetAuthorityList `json:"authorityList"`
}

type DeleteAuthorityReq struct {
	AuthorityId int64 `json:"authorityId "`
}

type DeleteAuthorityResp struct {
	Message string `json:"message"`
}

type UpdateAuthorityReq struct {
	AuthorityId   int64  `json:"authorityId"`
	AuthorityName string `json:"authorityName"`
	ParentId      int64  `json:"parentId"`
}

type UpdateAuthorityResp struct {
	Message string `json:"message"`
}

type SetDataAuthorityReq struct {
}

type SetDataAuthorityResp struct {
}

type TestReq struct {
	Id   int    `json:"id"`
	Name string `json:"name"`
}

type TestResp struct {
	Message string `json:"message"`
}

type PageInfo struct {
	Page     int `form:"page"`
	PageSize int `form:"pageSize"`
}

type GetDicListReq struct {
	Name     string `form:"name,optional"`
	Type     string `form:"type,optional"`
	Status   int64  `form:"status,optional"`
	Desc     string `form:"desc,optional"`
	Page     int    `form:"page,optional"`
	PageSize int    `form:"pageSize,optional"`
}

type GetDicListResp struct {
	DicList []*Dictionary `json:"dicList"`
	Total   int64         `json:"total"`
}

type Dictionary struct {
	Id        int    `json:"id"`
	CreatedAt int    `json:"createdAt"`
	UpdatedAt int    `json:"updatedAt"`
	DeletedAt int    `json:"deletedAt"`
	Name      string `json:"name"`
	Type      string `json:"type"`
	Status    int64  `json:"status"`
	Desc      string `json:"desc"`
}

type GetDicDetailsReq struct {
	Id int64 `form:"id"`
}

type GetDicDetailsResp struct {
	DetailsList []*DicDetail `json:"detailsList"`
}

type DicDetail struct {
	Id              int64  `json:"id"`
	SysDictionatyId int64  `json:"sysDictionatyId"`
	Date            int    `json:"date"`
	Lable           string `json:"lable"`
	Value           int64  `json:"value"`
	Status          int64  `json:"status"`
	Sort            int64  `json:"sort"`
}

type AddDicReq struct {
	Name   string `json:"name"`
	Type   string `json:"type"`
	Status int64  `json:"status"`
	Desc   string `json:"desc"`
}

type AddDicResp struct {
	Msg string `json:"msg"`
	Id  int64  `json:"id"`
}

type EditDicReq struct {
	Id     int    `json:"id"`
	Name   string `json:"name"`
	Type   string `json:"type"`
	Status int64  `json:"status"`
	Desc   string `json:"desc"`
}

type EditDicResp struct {
	Msg string `json:"msg"`
}

type DeleteDicReq struct {
	Id int64 `json:"id"`
}

type DeleteDicResp struct {
	Msg string `json:"msg"`
}

type AddDicDetailsReq struct {
	SysDictionatyId int64  `json:"sysDictionatyId"`
	Lable           string `json:"lable"`
	Value           int64  `json:"value"`
	Status          int64  `json:"status"`
	Sort            int64  `json:"sort"`
}

type AddDicDetailsResp struct {
	Msg string `json:"msg"`
	Id  int64  `json:"id"`
}

type EditDicDetailsReq struct {
	Id              int64  `json:"id"`
	Lable           string `json:"lable"`
	Value           int64  `json:"value"`
	Status          int64  `json:"status"`
	Sort            int64  `json:"sort"`
	SysDictionatyId int64  `json:"sysDictionatyId"`
}

type EditDicDetailsResp struct {
	Msg string `json:"msg"`
}

type DeleteDicDetailsReq struct {
	Id int64 `json:"id"`
}

type DeleteDicDetailsResp struct {
	Msg string `json:"msg"`
}

type Operation struct {
	Id           int64  `json:"id"`
	CreatedAt    int64  `json:"createdAt"`
	UpdatedAt    int64  `json:"updatedAt"`
	Ip           string `json:"ip"`
	Method       string `json:"method"`
	Path         string `json:"path"`
	Status       int64  `json:"status"`
	Latency      int64  `json:"latency"`
	Agent        string `json:"agent"`
	ErrorMessage string `json:"errorMessage"`
	Body         string `json:"body"`
	Resp         string `json:"resp"`
	UserId       int64  `json:"userId"`
}

type GetOperationListReq struct {
	Page     int `form:"page,optional"`
	PageSize int `form:"pageSize,optional"`
}

type GetOperationListResp struct {
	Total         int          `json:"total"`
	OperationList []*Operation `json:"operationList"`
}

type CreateOperationReq struct {
	Id           int64  `json:"id"`
	CreatedAt    int64  `json:"createdAt"`
	UpdatedAt    int64  `json:"updatedAt"`
	Ip           string `json:"ip,optional"`
	Method       string `json:"method,optional"`
	Path         string `json:"path,optional"`
	Status       int64  `json:"status,optional"`
	Latency      int64  `json:"latency,optional"`
	Agent        string `json:"agent,optional"`
	ErrorMessage string `json:"errorMessage,optional"`
	Body         string `json:"body,optional"`
	Resp         string `json:"resp,optional"`
	UserId       int64  `json:"userId,optional"`
}

type CreateOperationResp struct {
	Msg string `json:"msg"`
}
